spring.application.name=Pravin
# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers,retries,ratelimiters,bulkheads
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
#management.otlp.metrics.export.url=http://localhost:9090/api/v1/otlp/v1/metrics
management.otlp.metrics.export.step=30s
#management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4317/v1/traces
management.opentelemetry.tracing.export.otlp.transport=grpc
#management.opentelemetry.logging.export.otlp.endpoint=http://localhost:3100/otlp/v1/logs
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.enable.all.cache=true
management.metrics.enable.cache=true
logging.pattern.correlation=[${spring.application.name:},%X{trace_id:-},%X{span_id:-},%X{trace_flags:-}]

# =========================
# H2DB
# =========================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# =========================
# Configure Hibernate DDL generation
# =========================

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


# =========================
# API DOC
# =========================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.writer-with-default-pretty-printer=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
spring.main.allow-bean-definition-overriding=true
spring.mvc.problemdetails.enabled=true




# =========================
# REDIS CONFIG
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false
spring.data.redis.repositories.enabled=false

# =========================
# GLOBAL DEFAULT CONFIGS
# =========================

# ---- Circuit Breaker ----
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=3
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=3
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.slowCallRateThreshold=60
resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold=2s
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=1s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

# ---- Retry ----
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=300ms
resilience4j.retry.configs.default.enableExponentialBackoff=true
resilience4j.retry.configs.default.exponentialBackoffMultiplier=2

# ---- Bulkhead (Semaphore) ----
resilience4j.bulkhead.configs.default.maxConcurrentCalls=20
resilience4j.bulkhead.configs.default.maxWaitDuration=0

# ---- Rate Limiter ----
resilience4j.ratelimiter.configs.default.limitForPeriod=100
resilience4j.ratelimiter.configs.default.limitRefreshPeriod=1s
resilience4j.ratelimiter.configs.default.timeoutDuration=0

# =========================
# PAYMENT SERVICE IS CRITICAL
# =========================
resilience4j.circuitbreaker.instances.paymentService.baseConfig=default
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=30
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=60s

resilience4j.retry.instances.paymentService.baseConfig=default
resilience4j.retry.instances.paymentService.maxAttempts=2

resilience4j.bulkhead.instances.paymentService.baseConfig=default
resilience4j.bulkhead.instances.paymentService.maxConcurrentCalls=10

resilience4j.ratelimiter.instances.paymentService.baseConfig=default
resilience4j.ratelimiter.instances.paymentService.limitForPeriod=50

# =========================
# INVENTORY SERVICE - MEDIUM
# =========================
resilience4j.circuitbreaker.instances.inventoryService.baseConfig=default
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50

resilience4j.retry.instances.inventoryService.baseConfig=default

resilience4j.bulkhead.instances.inventoryService.baseConfig=default
resilience4j.bulkhead.instances.inventoryService.maxConcurrentCalls=25

resilience4j.ratelimiter.instances.inventoryService.baseConfig=default
resilience4j.ratelimiter.instances.inventoryService.limitForPeriod=150

# =========================
# NOTIFICATION SERVICE - LOW PRIORITY
# =========================
resilience4j.circuitbreaker.instances.notificationService.baseConfig=default
resilience4j.circuitbreaker.instances.notificationService.failureRateThreshold=70

resilience4j.retry.instances.notificationService.baseConfig=default
resilience4j.retry.instances.notificationService.maxAttempts=1

resilience4j.bulkhead.instances.notificationService.baseConfig=default
resilience4j.bulkhead.instances.notificationService.maxConcurrentCalls=50

resilience4j.ratelimiter.instances.notificationService.baseConfig=default
resilience4j.ratelimiter.instances.notificationService.limitForPeriod=300
